# Generated by Django 4.0 on 2022-01-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nazwa'),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nazwa Instytucji')),
                ('description', models.TextField(null=True, verbose_name='Opis')),
                ('type', models.CharField(choices=[(1, 'Fundacja'), (2, 'Organizacja pozarządowa'), (3, 'Zbiórka lokalna')], default=(1, 'Fundacja'), max_length=255, verbose_name='Typ')),
                ('category', models.ManyToManyField(related_name='institution', to='donate_app.Category', verbose_name='Kategoria')),
            ],
        ),
    ]
