# Generated by Django 4.0 on 2022-01-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('donate_app', '0002_alter_category_name_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Ilość')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Adres')),
                ('phone_number', models.IntegerField(null=True, verbose_name='Telefon')),
                ('city', models.CharField(max_length=255, null=True, verbose_name='Miasto')),
                ('zip_code', models.CharField(max_length=10, null=True, verbose_name='Kod pocztowy')),
                ('pick_up_date', models.DateField(verbose_name='Data odbioru')),
                ('pick_up_time', models.TimeField(verbose_name='Godzina odbioru')),
                ('pick_up_comment', models.TextField(null=True, verbose_name='Komentarz')),
                ('category', models.ManyToManyField(related_name='donation', to='donate_app.Category', verbose_name='Kategoria')),
                ('donation', models.ForeignKey(on_delete=models.SET(None), to='donate_app.institution', verbose_name='Instytucja')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=models.SET(None), to='auth.user', verbose_name='Użytkownik')),
            ],
        ),
    ]
