# Generated by Django 4.0 on 2022-01-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_app', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.ManyToManyField(to='donate_app.Category', verbose_name='Kategoria'),
        ),
    ]
