# Generated by Django 4.0 on 2022-01-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate_app', '0004_alter_donation_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donation',
            new_name='institution',
        ),
    ]
