# Generated by Django 4.0 on 2022-01-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_app', '0006_remove_donation_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), related_name='donation', to='donate_app.institution', verbose_name='Instytucja'),
        ),
    ]
