# Generated by Django 4.0 on 2022-01-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('donate_app', '0008_alter_donation_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Organizacja', 'verbose_name_plural': 'Organizacje'},
        ),
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=None, verbose_name='Zabrane'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=models.SET(None), related_name='donation', to='auth.user', verbose_name='Użytkownik'),
        ),
    ]
