# Generated by Django 4.0 on 2022-01-25 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('donate_app', '0010_alter_donation_is_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokensModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_token', models.CharField(max_length=255, null=True, verbose_name='Activation Token')),
                ('active_token_created', models.DateField(auto_now=True)),
                ('reset_token', models.CharField(max_length=255, null=True)),
                ('reset_token_created', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='auth.user', verbose_name='Użytkownik')),
            ],
        ),
    ]
